# Continuous Integration for the JS Tests
name: "CI JS Tests"

on:
  # Any pull request activity (open, synchronize, reopen)
  pull_request:
  # When called from another workflow
  workflow_call:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name:
          "Cache the node modules. If a match is found for the key, the cache is restored. Otherwise, a new cache will
          be created."
        uses: "actions/cache@v4"
        with:
          key: "node-modules-${{ github.sha }}"
          path: node_modules

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v2"
        with:
          bun-version: "latest"

      - name: "Install the Node.js dependencies"
        run: "bun install --frozen-lockfile"

      - name: "Run the tests"
        run: "bun run test"

      - name: "Add summary"
        run: |
          echo "## CI Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
